[workspace]
authors = ["juanmanuel.cabrera"]
channels = ["conda-forge"]
name = "insar-platform"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12"
rich = "*"
pyyaml = ">=6.0.3,<7"
python-dotenv = ">=1.2.4,<2"
requests = ">=2.34.2,<3"

[feature.dev.dependencies]
pytest = "*"
ruff = "*"

[tasks]
test = "pytest tests/"
format = "ruff format ."
format-check = "ruff format --check ."
lint = "ruff check ."

[environments]
dev = { features = ["dev"], solve-group = "default" }
