
# Configuration file for the InSAR project

URL: "https://catalogue.dataspace.copernicus.eu/odata/v1/Bursts"

# Date range for the acquisitions in UTC
START_DATE: "2025-01-01 00:00:00"
END_DATE: "2025-12-31 00:00:00"

COPERNICUS_CATALOGUE: ""

AOI_GEOJSON: "data/aoi/alto_guadalentin.geojson"